associatedemployers/granite

- app/components/form/action-button.js
- app/controllers/account/employee/index/edit.js
- app/controllers/account/employee/index/edit/index.js
- app/controllers/account/employee/index/edit/job.js
- app/models/employee.js
- app/router.js
- app/routes/account/employee/index/edit.js
- app/routes/account/employee/index/edit/index.js
- app/routes/account/employee/index/edit/job.js
- app/templates/account/employee/index.hbs
- app/templates/account/employee/index/edit.hbs
- app/templates/account/employee/index/edit/index.hbs
- app/templates/account/employee/index/edit/job.hbs
- app/templates/account/employee/onboard/index.hbs
- app/templates/account/employees/add/new.hbs
- app/utils/resolve-for-type-key.js
- tests/unit/controllers/account/employee/index/edit-test.js
- tests/unit/controllers/account/employee/index/edit/index-test.js
- tests/unit/controllers/account/employee/index/edit/job-test.js
- tests/unit/routes/account/employee/index/edit-test.js
- tests/unit/routes/account/employee/index/edit/index-test.js
- tests/unit/routes/account/employee/index/edit/job-test.js
> [Feature] Employee editing

- app/components/list-item/assigned-asset-item.js
- app/templates/account/employee/index/equipment.hbs
Added class of ui center to the card and removed “four” from cards.
:four_leaf_clover:
> Made cards responsive. Closes #72.

- app/controllers/account/employee/index/index.js
- app/styles/granite/global/utility.less
- app/styles/granite/page/employee.less
- app/templates/account/employee/index.hbs
- app/templates/account/employee/index/index.hbs
- app/templates/account/employee/onboard/job-information.hbs
Styled contact buttons.
Created the ability to select no supervisor, no department, and no
location.
Made the page tolerant of very little information being entered for the
employee.
> [Enhancements] Employee page changes closes #80

- app/components/ui-menu.js
- app/styles/granite/ui/responsive-menus.less
- app/styles/site/globals/site.variables
- app/templates/account/employee/index.hbs
- app/templates/components/ui-menu.hbs
- tests/integration/components/ui-menu-test.js
> [Enhancement] Make menus great again

- app/components/input/employee-custom-fields.js
- app/controllers/account/employee/onboard.js
- app/controllers/account/employee/onboard/custom-fields.js
- app/models/company.js
- app/models/employee.js
- app/router.js
- app/routes/account/employee/onboard/custom-fields.js
- app/styles/granite/page/employee.less
- app/templates/account/employee/index.hbs
- app/templates/account/employee/index/index.hbs
- app/templates/account/employee/onboard/custom-fields.hbs
- app/templates/account/employee/onboard/index.hbs
- app/templates/components/input/custom-field.hbs
- app/templates/components/input/employee-custom-fields.hbs
- tests/integration/components/input/employee-custom-fields-test.js
- tests/unit/controllers/account/employee/onboard/custom-fields-test.js
- tests/unit/routes/account/employee/onboard/custom-fields-test.js
Add custom fields in the onboarding process that are displayed on the
employee summary page.
> Employee Custom Fields.  Closes #82 Closes #33

- .eslintrc.json
- .jshintrc
- app/controllers/account/employee/index/edit-picture.js
- app/controllers/account/employee/onboard.js
- app/controllers/account/employee/onboard/picture.js
- app/router.js
- app/routes/account/employee/index/edit-picture.js
- app/routes/account/employee/onboard/picture.js
- app/styles/granite/page/employee.less
- app/styles/granite/page/onboarding.less
- app/templates/account/employee/index.hbs
- app/templates/account/employee/index/edit-picture.hbs
- app/templates/account/employee/onboard/picture.hbs
- bower.json
- package.json
- tests/integration/components/display/version-info-test.js
- tests/integration/components/elements/x-footer-test.js
- tests/unit/controllers/account/employee/index/edit-picture-test.js
- tests/unit/controllers/account/employee/onboard/picture-test.js
- tests/unit/routes/account/employee/index/edit-picture-test.js
- tests/unit/routes/account/employee/onboard/picture-test.js
closes #102, #96 
Thanks @jscottchapman
> [Feature] Employee picture upload

- app/components/card-pipeline/stage-card.js
- app/controllers/account/job-opening/campaign/applicant-tracking.js
- app/templates/account/job-opening/campaign/applicant-tracking.hbs
- app/templates/components/card-pipeline.hbs
- app/templates/components/card-pipeline/stage-card.hbs
- app/templates/components/card-pipeline/stage-column.hbs
- bower.json
Added the ability to undo the hiring action in the case of someone
accidentally hitting the hire button on the wrong person.
> Disable controls if the candidate is marked as hired or disqualified.

- app/instance-initializer/rsvp-error-handler.js
- config/environment.js
- package.json
- yarn.lock
> Add rollbar integration

- app/components/elements/company-navigation.js
- app/components/elements/file-uploader.js
- app/controllers/account/employees/add/census.js
- app/templates/account/employees/add/census.hbs
- app/templates/components/elements/company-navigation.hbs
- package.json
- yarn.lock
> Fix census file upload

- app/controllers/account/action-items/new.js
- app/templates/account/action-item/todo.hbs
- app/templates/account/action-items/new.hbs
> Fix assignment selection, fix todo duping

- package.json
- yarn.lock
> Fixes popup positioning

- app/templates/components/list-item/employee-item.hbs
> added termination date label to employee list item - fixes #118

- app/components/form/action-button.js
- app/controllers/application.js
- app/controllers/login.js
- app/controllers/recover.js
- app/mixins/ajax-status.js
- app/router.js
- app/routes/recover.js
- app/templates/login.hbs
- app/templates/recover.hbs
- tests/unit/controllers/recover-test.js
- tests/unit/routes/recover-test.js
> [Feature] Password Recovery UIs

- app/components/list-item/change-item.js
- app/controllers/account/employees/changes.js
- app/models/change.js
- app/router.js
- app/routes/account/employees.js
- app/routes/account/employees/changes.js
- app/serializers/change.js
- app/styles/site/elements/list.overrides
- app/templates/account/employees.hbs
- app/templates/account/employees/changes.hbs
- app/templates/components/display/resource-list.hbs
- app/templates/components/list-item/change-item.hbs
- tests/integration/components/list-item/change-item-test.js
- tests/unit/controllers/account/employees/changes-test.js
- tests/unit/models/change-test.js
- tests/unit/routes/account/employees/changes-test.js
- tests/unit/serializers/change-test.js
> [Feature] Change process

- app/components/modals/ats-add-applicant.js
- app/models/job-application.js
- app/styles/granite/components/pipeline.less
- app/templates/components/card-pipeline/stage-card.hbs
> display for entry method added and functional - closes #135

- app/components/modals/ats-close-job-opening.js
- app/templates/account/job-opening/campaign.hbs
- app/templates/components/confirm-modal.hbs
- app/templates/components/modals/ats-close-job-opening.hbs
> users are now reminded to close their manual applicant sources when closing a job opening - closes #136

- app/templates/components/list-item/job-item.hbs
> Closed #198 BUG-Missing-space-in-job-descriptions-list-item

- app/controllers/application.js
- app/routes/application.js
> [Bug]Remove (comment out) Leave Management in menu/closed#227

- app/templates/account/employee/offboard.hbs
- app/templates/account/employee/offboard/index.hbs
> [Enhancement] under offboarding remove "this is permeant"/closed #216

- app/routes/account/employees/index.js
> [Enhancement] default only show active employees in the employees/closed #217

- app/styles/granite/components/pipeline.less
> styles added to space the match score from the applicant source

- app/templates/pricing.hbs
> changed the wording on pricing page to employees from users

- app/templates/components/card-pipeline/stage-card.hbs
> [Feature] add email link to applicant card next to the name (ATS)/Closed

- app/styles/granite/global/print.less
- app/styles/granite/page/corrective-action.less
- app/templates/account/employee/index/counseling/issue/corrective-action/print.hbs
> date field added, notifications hidden from printing globally

- app/routes/account/employees/add/new.js
> added default properties to begin onboarding immediately upon employee creation

- app/routes/account/anatomy/locations/index/new.js
> [Enhancement] when choosing a state in locations shows Alabama/Closed

- app/templates/account/job-opening/campaign/job-application/index.hbs
> responses to job opening show regardless of scoreRelative

- app/controllers/account/action-item/todo.js
> only one todo items shows after creation now

- app/controllers/account/employee/index/counseling/issue/corrective-action.js
- app/controllers/account/settings/index/processes.js
> corrective action processes and followups only created once now

- app/controllers/account/employee/index/edit/custom-fields.js
- app/controllers/account/employee/onboard/custom-fields.js
- app/templates/account/employee/index/edit/custom-fields.hbs
- app/templates/account/employee/onboard/custom-fields.hbs
> bug custom fields closes when adding a new field./closed #211

- app/templates/account/action-item.hbs
> Enhancement/#207change Transfer action to transfer to new owner/closed

- app/controllers/account/settings/index/index.js
- app/templates/account/settings/index/index.hbs
Closes #177 
This was never merged for whatever reason
> [Enhancements] Add address, company name. Remove palette

- app/styles/granite/page/corrective-action.less
- app/templates/account/employee/index/counseling/issue/new.hbs
> added a call us tag

- app/components/display/employee-picture.js
> set default avatar so that no undefined requests take place

- app/controllers/account/documents/index.js
- app/controllers/account/documents/new.js
> document assign works as it should, dropzone clears after uploading document

- app/services/auth.js
> #271-session-expires-even

- app/templates/account/index.hbs
> removed feed buttons

- app/components/messaging/message-thread.js
- app/controllers/account/employees/messages/thread.js
- app/mixins/file-handling.js
- app/templates/components/messaging/message-thread.hbs
closes associatedemployers/igneous#102
> messaging now uses mixin to upload files, systemUse marked as true

- app/components/display/product/features-list.js
- app/components/elements/x-navigation.js
- app/index.html
- app/routes/account.js
- app/routes/account/action-item/index.js
- app/routes/account/employee/index/counseling/issue/corrective-action/print.js
- app/routes/account/employee/onboard-complete.js
- app/routes/account/employee/onboard/equipment.js
- app/styles/common/variables.less
- app/styles/granite/components/elements/nav.less
- app/styles/granite/page/our-product.less
- app/templates/components/display/product/features-list.hbs
- app/templates/components/elements/x-navigation.hbs
- app/templates/our-product.hbs
> #265 fix mobile display for menus and features page

- app/components/list-item/activity-item.js
> commenting on activity is not duplicated any longer

- app/templates/account/anatomy/departments/index.hbs
- app/templates/account/anatomy/locations/index.hbs
> removed slate payroll import options from location/department pages

- app/controllers/account/recruiting/index/index.js
- app/routes/account/recruiting/index/index.js
- app/templates/account/recruiting/index/index.hbs
> sort and filters for campaigns

- app/components/list-item/activity-item.js
> no more duplicate likes on activities

- app/templates/account/employees/add/census/review.hbs
> loading status for census dry run

- app/styles/site/elements/input.overrides
- app/templates/signup/index.hbs
- tests/acceptance/signup-test.js
> state selector won't highlight green on the bottom anymore

- app/models/employee.js
closes associatedemployers/igneous#113
> fixed default payRateType on employee model

- app/controllers/account/asset/index.js
- app/routes/account/asset/index.js
- app/templates/account/asset.hbs
- app/templates/account/asset/index.hbs
- app/templates/components/list-item/asset-stock-item.hbs
closes #280
open to suggestions on design
> moved some things around on assets page, added pagination

- app/templates/account/employees/add/census/review.hbs
> added ability to disregard census column

- app/components/elements/account-navigation.js
- app/components/input/document-selection-modal.js
- app/components/validated-input.js
- app/controllers/signup.js
- app/controllers/signup/index.js
- app/mixins/ajax-status.js
- app/styles/granite/page/signup.less
- app/templates/account/employees/add/census/review.hbs
- app/templates/components/validated-input.hbs
- app/templates/signup/index.hbs
- package.json
- tests/acceptance/assets-test.js
- tests/acceptance/recruiting/new-position-test.js
- tests/acceptance/recruiting/recent-activity-test.js
- tests/acceptance/signup-test.js
> urlPrefix should be unique

- app/controllers/account/employee/onboard/equipment.js
- app/controllers/account/job-opening/campaign/applicant-tracking.js
- app/models/employee.js
- app/routes/account/employee/onboard/equipment.js
- app/routes/account/employee/onboard/job-information.js
- app/templates/account/employee/onboard/equipment.hbs
- app/templates/account/employee/onboard/job-information.hbs
- app/templates/components/input/equipment-picker.hbs
- yarn.lock
closes #340 
requires associatedemployers/igneous#128
> assets are suggested based on employee's job

- app/controllers/account/documents/new.js
> added onboarding and offboarding tags for documents

- app/components/input/document-selection-modal.js
- app/controllers/account/employee/offboard/options.js
- app/controllers/account/employee/onboard/documents.js
- app/styles/granite/components/document-selector.less
- app/templates/account/employee/offboard/options.hbs
- app/templates/account/employee/onboard/documents.hbs
- app/templates/components/input/document-selection-modal.hbs
> [Feature] #395 add upload to document selection modal

- app/components/input/document-selection-modal.js
- app/controllers/account/asset/documents.js
- app/controllers/account/employee/onboard/equipment.js
- app/models/asset-item.js
- app/models/asset.js
- app/routes/account/employee/onboard/equipment.js
- app/styles/granite/components/pipeline.less
- app/styles/granite/global/segments.less
- app/templates/account/asset/documents.hbs
- app/templates/account/asset/index/new.hbs
- app/templates/account/assets/new.hbs
- app/templates/account/employee/onboard/equipment.hbs
- app/templates/components/input/document-selection-modal.hbs
> [Feature] #336 associated documents on assets

- app/components/modals/ats-add-applicant.js
> Dropzone not working

- app/controllers/account/employee/offboard/documents.js
- app/router.js
- app/routes/account/employee/offboard.js
- app/routes/account/employee/offboard/documents.js
- app/templates/account/employee/offboard/documents.hbs
> documents in offboarding

- app/components/visualizations/organization-tree.js
- app/components/visualizations/reorganization-tree.js
> Add 'zoom' to the org chart

- app/components/list-item/talent-pool-applicant.js
- app/controllers/account/employee/offboard/documents.js
- app/controllers/account/job-description.js
- app/controllers/account/job-opening/campaign/talent-pool.js
- app/mixins/route-abstractions/resource.js
- app/router.js
- app/routes/account/job-opening/campaign/talent-pool.js
- app/styles/granite/global/flex.less
- app/templates/account/job-opening/campaign.hbs
- app/templates/account/job-opening/campaign/index.hbs
- app/templates/account/job-opening/campaign/talent-pool.hbs
- app/templates/components/list-item/talent-pool-applicant.hbs
- mirage/config.js
- tests/acceptance/recruiting/recent-activity-test.js
- tests/acceptance/recruiting/talent-pool-test.js
- tests/integration/components/list-item/talent-pool-applicant-test.js
- tests/unit/controllers/account/job-opening/campaign/talent-pool-test.js
- tests/unit/routes/account/job-opening/campaign/talent-pool-test.js
closes #299 
Includes a bug fix for "name required" popup when hiring from job descriptions, and visual fixes for empty charts in campaign summary.
> [Feature] Talent pool MVP

- app/router.js
- config/environment.js
- package.json
- tests/acceptance/company-users-test.js
- tests/acceptance/documents/document-test.js
- yarn.lock
Add ember-router-scroll and $$$
closes #414
> [Fix] Transition scroll position

- .travis.yml
- app/controllers/account/employee/index/counseling/new.js
- app/models/employee-issue.js
- app/routes/account/employee/index/counseling/new.js
> [Enhancement] Swap exclusion model for corrective actions

- app/components/census/table-cell.js
- app/components/census/table-row.js
- app/components/list-item/dry-run-employee.js
- app/controllers/account/employees/add/census/review.js
- app/styles/granite/page/census-upload.less
- app/templates/account/employees/add/census/review.hbs
- app/templates/components/census/table-cell.hbs
- app/templates/components/census/table-row.hbs
- app/templates/components/list-item/dry-run-employee.hbs
closes #430 and closes #442 and closes #453
> highlight census rows with missing required fields or mismatched lookups

- mirage/config.js
- mirage/factories/employee.js
- tests/acceptance/documents/document-test.js
- tests/acceptance/employees-test.js
> tests passing again

- app/templates/account/employees/index.hbs
- app/templates/account/recruiting/index/index.hbs
> [Enhancement] Add close icon to filters

- app/components/input/document-selection-modal.js
- app/components/list-item/asset-stock-item.js
- app/controllers/account/asset/documents.js
- app/controllers/account/asset/index.js
- app/templates/account/asset/documents.hbs
- app/templates/account/asset/index.hbs
- app/templates/components/list-item/asset-stock-item.hbs
- app/templates/components/list-item/document-item.hbs
> edit asset and stock documents

- app/config/statics.js
> added null to jobtype enums

- app/components/visualizations/organization-tree.js
- app/components/visualizations/reorganization-tree.js
> [Enhancement] Reflow the org chart to the right

- app/templates/account/job-opening/campaign/job-application/index.hbs
> [Fix] accounted for multi select in screening responses

- app/components/modals/add-asset-category.js
- app/controllers/account/employee/onboard/equipment.js
> [Fix] equipment assigning modals working now in onboarding

- app/controllers/account/recruiting/job-descriptions/new.js
- app/templates/components/input/quick-form-input.hbs
> changed text editor when creating job descriptions

- app/components/modals/add-asset-category.js
- app/controllers/account/assets/new.js
- app/templates/account/assets/new.hbs
- app/templates/components/modals/add-asset-category.hbs
> [Fix] asset sharable toggle 

- app/components/census/dry-run-employee-relationship.js
- app/components/census/table-cell.js
- app/templates/components/census/dry-run-employee-relationship.hbs
> [Fix] changes for supervisor census lookup

- app/templates/account/anatomy/index.hbs
> [Enhancement] Move the employee search in org chart to the top

- app/styles/granitestyles/page/signup.less
- app/templates/components/display/ui-step.hbs
> [Bug] Remove links from steps in signup

- app/routes/account/job-opening/campaign.js
> [Fix] continue campaign setup flag

- app/routes/account/employee/index/job.js
- app/templates/account/employee/index/job.hbs
> [Enhancement] remove employee job route

- app/templates/account/employee/index/documents/index.hbs
> [Enhancement] no file assignments available text

- app/controllers/account/job-opening/setup/screening.js
> [Fix] no screening questions

- app/routes/account/employee/index/edit/job.js
- app/templates/account/employee/index.hbs
- app/templates/account/employee/index/edit/job.hbs
> [Enhancement] link job description on employee page

- app/styles/granitestyles/page/contact.less
- app/templates/contact.hbs
- tests/acceptance/main-page-and-sub-pages/contact-page-test.js
> [Enhancement] remove social links from contact page

- app/routes/account/action-item/index.js
- config/deploy.js
- config/environment.js
- ember-cli-build.js
- package.json
- yarn.lock
> [Feature] Source maps #510

- app/router.js
- app/routes/terms-of-service.js
- app/styles/granitestyles/ui/footer.less
- app/templates/components/elements/x-footer.hbs
- app/templates/terms-of-service.hbs
> [Feature] Add TOS page

- app/templates/pricing.hbs
> [Chore] update pricing structure

- app/controllers/signup/billing.js
- app/models/company.js
- app/templates/components/input/ui-input.hbs
- app/templates/signup/billing.hbs
- mirage/config.js
- mirage/models/discount.js
- tests/acceptance/signup-test.js
> [Feature] Add promo code entry

- app/config/breadcrumb.js
- app/controllers/application.js
- app/router.js
- app/routes/account/action-item/index.js
- app/routes/account/action-items/index.js
- app/routes/account/action-items/new.js
- app/services/search.js
- app/templates/account/action-item.hbs
- app/templates/account/action-item/edit.hbs
- app/templates/account/action-items/index.hbs
- app/templates/account/action-items/new.hbs
- tests/acceptance/action-items/action-item-test.js
- tests/acceptance/action-items/action-items-test.js
- tests/acceptance/action-items/edit-action-item-test.js
- tests/acceptance/action-items/new-action-item-test.js
> [Enhancement] Change action items to projects

- app/models/applicant-source.js
- app/templates/components/list-item/applicant-source-select.hbs
> [Enhancement] Display costPerCycle on automatic sources

- app/models/event.js
- app/templates/components/modals/ats-scheduler.hbs
> [Feature] option to not notify applicant of meeting

- app/components/modals/ats-link-sharing.js
- app/controllers/account/job-opening/campaign/applicant-tracking.js
- app/controllers/application.js
- app/controllers/shared/job-application.js
- app/models/job-application.js
- app/router.js
- app/routes/shared.js
- app/routes/shared/job-application.js
- app/styles/granitestyles/page/shared.less
- app/templates/account/job-opening/campaign/applicant-tracking.hbs
- app/templates/application.hbs
- app/templates/components/card-pipeline.hbs
- app/templates/components/card-pipeline/stage-card.hbs
- app/templates/components/card-pipeline/stage-column.hbs
- app/templates/components/modals/ats-link-sharing.hbs
- app/templates/shared.hbs
- app/templates/shared/job-application.hbs
- tests/acceptance/recruiting/applicants-test.js
> [Feature] Sharable job apps

- app/templates/account/index.hbs
> [Enhancement] change "action-item" to "project" on dash

- app/services/notifications.js
> [Rollbar] TypeError Cannot assign to read only property 'permission'

- app/models/job-opening.js
> [Bug][Rollbar] TypeError Cannot read property 'replace' of null

- app/templates/account/employee/index/edit/job.hbs
> [Fix] Padding for job description when editing employee

- app/templates/components/list-item/department-item.hbs
- app/templates/components/list-item/location-item.hbs
> [Fix] dept and loc display issues

- app/models/employee.js
> [Fix] Employee full name not updating on edit

- app/routes/account/employee/index/equipment.js
> [Bug] Modal issue when adding assets

- app/controllers/account/asset/edit.js
- app/routes/account/asset/edit.js
- app/templates/account/asset/edit.hbs
- mirage/config.js
- tests/acceptance/asset/asset-item-edit-test.js
- tests/acceptance/asset/edit-assets-test.js
> [Fix] Asset category editing

- app/controllers/account/employee/index/edit.js
- app/routes/account/employee/index/edit.js
> [Fix] Editing job description on employees

- app/components/intro-js.js
> [Fix] Skipping on intro tutorial throws error

- app/templates/account/employee/index/edit/job.hbs
> [Bug] cant enter a decimal in pay rate

- app/controllers/account/job-opening/campaign/applicant-tracking.js
> [Bug] [Enhancement] Hide/show Disqualified Applicants doesn't apply to pending 'pendingApplications'

- app/routes/account/employee/onboard/index.js
- app/routes/account/employees/add/new.js
> [Enhancement] On-boarding auto fill State to match company state

- app/controllers/account/job-opening/campaign/settings.js
- app/controllers/account/job-opening/setup/settings.js
> [Fix] UI changes regarding orphaned applications in pipeline

- app/templates/account/job-opening/campaign/job-application/index.hbs
> [Enhancement] No screening response should show "No response" in light text color below question

- app/models/employee.js
- app/models/validations/employee.js
- app/templates/account/employee/index/edit/index.hbs
- app/templates/account/employee/index/index.hbs
- app/templates/account/employee/onboard/index.hbs
closes #646
close with associatedemployers/quartz#83, associatedemployers/igneous#259
> [Feature] Private email field

- app/components/input/quick-form-input.js
- app/components/modals/ats-add-label.js
- app/templates/components/input/quick-form-input.hbs
> [Bug] [Enhancement] Applicant label has no default color even though black displays

- app/routes/account/employees/messages.js
> [Fix] Sort employee by alpha for new messages

- app/controllers/account/employees/add/census/index.js
- app/controllers/account/employees/add/census/review.js
- app/controllers/account/employees/add/new.js
- app/controllers/account/job-opening/campaign/applicant-tracking.js
- app/controllers/signup/billing.js
- app/initializers/analytics.js
- app/routes/account/employee/complete-offboarding.js
- app/routes/account/employee/offboard.js
- app/routes/account/employee/onboard-complete.js
- app/routes/account/job-opening/setup-complete.js
- app/services/analytics.js
- app/services/auth.js
- package.json
- tests/unit/services/analytics-test.js
- yarn.lock
> [Feature] Adds events to GA metrics

- app/models/file-assignment.js
> [Enhancement] Change file assignment sig default

- app/models/action-item.js
- app/routes/account/action-item.js
> [Bug] Fix dash usage in project names

- app/serializers/employee.js
- app/templates/account/employee/index/edit/job.hbs
> [Enhancement] Adds non-rel option for several items, remove serializer null removal

- app/templates/account/employee/index.hbs
> [Fix] Offboard link shows for offboarded employees

- app/components/list-item/employee-document-item.js
- app/components/list-item/file-assignment.js
- app/controllers/account/document.js
- app/controllers/account/employee/index/documents/new.js
- app/models/file-assignment.js
- app/templates/account/document.hbs
- app/templates/account/employee/index.hbs
- app/templates/account/employee/index/documents/new.hbs
- app/templates/components/list-item/employee-document-item.hbs
- app/templates/components/list-item/file-assignment.hbs
- tests/acceptance/action-items/edit-action-item-test.js
- tests/acceptance/action-items/new-action-item-test.js
closes #675
close with associatedemployers/igneous#270
> [Feature] ability to send file assignments on a future set date

- app/controllers/account/employee/offboard/reorganization.js
- app/templates/account/employee/offboard/reorganization.hbs
> [Fix] Confirm modal not showing emp name on offboarding

- app/components/recruiting-status-bar.js
- app/routes/account/job-opening/campaign/index.js
- app/templates/account/job-opening/campaign/index.hbs
- app/templates/components/recruiting-status-bar.hbs
- package.json
> [Enhancement] Campaign status bar

- app/controllers/account/employees/index.js
- app/mixins/route-abstractions/resource.js
- app/routes/account/employees/index.js
- app/templates/account/employees/index.hbs
- tests/acceptance/employees-test.js
> [Enhancement] Employee Sorting

- app/routes/account/document.js
> [Fix] Document Page Title Undefined

- app/controllers/account/employee/index/index.js
- app/models/employee.js
- app/templates/account/employee/index/index.hbs
- app/templates/account/employee/offboard/details.hbs
closes #668
close with associatedemployers/igneous#277
> [Feature] add a note section in offboarding for internal use only

- app/components/list-item/document-item.js
- app/components/list-item/employee-document-item.js
- app/controllers/account/settings/index/index.js
- app/models/company.js
- app/models/employee.js
- app/models/file-assignment.js
- app/templates/account/employee/index/documents/index.hbs
- app/templates/account/employee/onboard/documents.hbs
- app/templates/components/elements/file-uploader.hbs
- app/templates/components/list-item/employee-document-item.hbs
- yarn.lock
> [Feature] i9/w4 adjustments, add EIN field

- app/controllers/account/job-opening/campaign.js
- app/styles/granitestyles/global/typography.less
- app/templates/account/job-opening/campaign.hbs
- app/templates/components/recruiting-status-bar.hbs
> [Enhancement] Manually close job campaign

- app/routes/account/job-opening/campaign/index.js
> [Enhancement] Google Page View Analytics for Recruiting

- app/serializers/employee.js
> [Feature] Final Address Collection

- app/controllers/account/document.js
- app/controllers/account/document/index.js
closes #717
[RN] fixed closing modal error in documents assignments
> [Bug] Nothing handled the action 'respondedAssignment

- app/routes/account/import/discovered.js
added this fix for octane, seems octane may have removed some properties
> [Bug] pretty sure this is needed because of the upgrade to octane

- app/models/job-application.js
- app/templates/account/job-opening/campaign/job-application.hbs
- mirage/factories/job-application.js
close with associatedemployers/igneous#296
close with associatedemployers/quartz#95
> [Hot Fix] Changed 'isCompleted' to 'completedOn'

- app/controllers/account/settings/user.js
- app/router.js
- app/templates/account/settings.hbs
- app/templates/account/settings/user.hbs
- mirage/config.js
- tests/acceptance/settings/user-test.js
- yarn.lock
closes #652 
close with associatedemployers/igneous#289
close with associatedemployers/quartz#93
> [Feature] Change password

- app/routes/account/employees/changes.js
- app/templates/components/list-item/change-item.hbs
closes #640
close with associatedemployers/quartz#96
close with associatedemployers/igneous#298
> [Enhancement] Add before value to a change item

- app/templates/account/employee/offboard/options.hbs
- yarn.lock
> [Bug] remove 'add documents' in options/offboarding

- app/controllers/account/employee/onboard/equipment.js
- app/templates/account/employee/onboard/equipment.hbs
- yarn.lock
> [Bug] onboarding/asset cant create/assign/unassign a new asset

- app/controllers/account/employee/onboard/documents.js
- app/models/file-assignment.js
- app/routes/account/employee/offboard/documents.js
closes #729
close with associatedemployers/igneous#304
> [Bug] offboading/documents seems to be using onboading array

- app/templates/account/employee/index/counseling/issue.hbs
> [Enhancement] Back to all issues in corrective actions

- app/components/intro-js.js
- app/components/modals/index.js
- app/controllers/account/employee/onboard/equipment.js
- app/controllers/account/job-opening/campaign/settings.js
closes #666  😈
added safeguards
> [Bug] Cannot read property 'isDestroyed' of null

- app/controllers/account/employee/index.js
- app/styles/granitestyles/ui/responsive-menus.less
- app/templates/account/employee/index.hbs
- package.json
- yarn.lock
> [Bug] Employee page "more" sub-menu doesn't show on mobile

- app/templates/account/education.hbs
> [Fix] Fix Link in Education Module

- app/models/open-enrollment.js
closes #772
close with associatedemployers/igneous#324
> [Feature] Open enrollment model

- app/templates/pricing.hbs
> [Chore] Updating pricing

- app/models/employee.js
- app/routes/account/employee/index/edit/job.js
- app/templates/account/employee/index/edit/job.hbs
- app/templates/account/employee/onboard/job-information.hbs
closes #777  
close with associatedemployers/igneous#327
> [Enhancement] Add "minimumHours" number field to employee

- app/models/plan.js
> [Enhancement] Add new plan data keys

- app/routes/account/employee/index/edit/job.js
closes #786
adding 'get' got the company id
> Cant get company id in job page

- app/templates/account/index.hbs
- app/templates/shared/job-application.hbs
closes #789
fixed dashboard and share/jobApp
> [Bug] "Show more" in A tags aren't working

- app/models/employee.js
closes #802 
close with associatedemployers/igneous#347
> [Enhancement] Add martial status and gender to employee model

- app/config/breadcrumb.js
- app/config/statics.js
- app/router.js
- app/routes/account/hr.js
- app/styles/granitestyles/page/hr-resources.less
- app/templates/account/hr.hbs
WIP needs Access to wolters kluwer (maybe in an iframe)
> [WIP] [Feature] HR resources

- app/components/modals/view-form-response.js
> [Bug] Form response modal broken in /account/employees/forms/responses/:id

- app/components/elements/company-navigation.hbs
- app/components/elements/company-navigation.js
- app/controllers/account.js
- app/styles/granitestyles/components/elements/nav.less
- app/styles/granitestyles/global/logos.less
- app/templates/account.hbs
> [Enhancement] Replace beta logo

- app/templates/account/hr.hbs
> Tests are broken on master

- app/templates/account/benefits/plans/index.hbs
> [Bug] Nothing displays w/o plans

- app/components/form/form-element.js
- app/components/input/document-selection-modal.js
> [Bug] Document selection modal should exclude systemUse: true

- app/components/form/form-element.js
> [Bug] Move arrow not in correct location screening in campaign wizard

- app/controllers/account/employee/index/counseling/issue/corrective-action.js
> [Fix] error when following up on corrective action

- app/components/display/ea-help-link.js
- app/styles/granitestyles/components/display/ea-help-link.less
- app/templates/application.hbs
- app/templates/components/display/ea-help-link.hbs
> [Feature] Adds EA link

- app/routes/account/index.js
> [Fix] First Steps

- app/components/list-item/training-assignment.hbs
- app/controllers/account/employee/index/education/training-assignment.js
- app/controllers/account/employee/index/education/training-assignment/index.js
- app/router.js
- app/routes/account/employee/index/education/training-assignment.js
- app/routes/account/employee/index/education/training-assignment/index.js
- app/templates/account/employee/index/education/training-assignment.hbs
- app/templates/account/employee/index/education/training-assignment/index.hbs
> [Enhancement] Able to delete training assignments

- app/models/plan.js
closes #821 
close with associatedemployers/igneous#350
close with associatedemployers/quartz#136
> [Feature] Add `carrier` key to plan model

- app/components/benefits/enrollments/enrollments-list.hbs
- app/components/benefits/enrollments/enrollments-list.js
- app/components/display/resource-list.hbs
- app/components/display/resource-list.js
- app/controllers/account/benefits/enrollments.js
- app/controllers/account/benefits/enrollments/index.js
- app/models/dependent.js
- app/models/election.js
- app/models/enrollment.js
- app/router.js
- app/routes/account/benefits/enrollments/index.js
- app/serializers/dependent.js
- app/serializers/enrollment.js
- app/templates/account/benefits/enrollments.hbs
- app/templates/account/benefits/enrollments/index.hbs
> [Feature] Enrollment list

- app/controllers/account/benefits/plans/contributions/edit-all.js
> [Bug] Error saving contributions

- app/components/benefits/enrollments/enrollments-list.js
> [Bug] Review page enrollment label not showing

- app/components/form/w-4.hbs
- app/components/form/w-4.js
- app/components/input/ui-input.hbs
- app/components/modals/ats-hire.hbs
- app/config/statics.js
- app/controllers/account/employee/onboard/index.js
- app/core/wizard.js
- app/models/bank-account.js
- app/models/company.js
- app/models/employee.js
- app/routes/account/employee/onboard.js
- app/serializers/bank-account.js
- app/serializers/employee.js
- app/templates/account/employee/onboard/index.hbs
- app/templates/account/employees/add/new.hbs
> [Feature] In onboarding, add additional, optional fields to populate to slate pay
